using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace time2punch
{
    class ShiftCalc
    {
        /* Calculate the time between two punch objects.
         * (StartShift + StartLunch) + (End Lunch + End Shift)
         * MUST be generated by the same username.
         */
    }
}
